Simplify scala step1
nikhilnanivadekar/JvmLanguageCompare pull request #2
Opened 2018-11-12 17:18 UTC by LogicalTime

Check out the individual commits. I tried to do the most simple improvements possible for this pull request. There is more I could do. Let me know if there are any questions or if you want me to do more. I could:
- Switch from enumerations to the style most scala programmers would use.
- remove 'this.' in  many places because it is not needed.
- show a more functional style of dealing with deck and player's hands state

2018-11-13 06:23 UTC, donraab requested changes
I think this change is breaking the tests.  We need to shuffle the deck three times.  It looks with this change like the deck is only being shuffled once.

2018-11-13 06:24 UTC, donraab approved these changes
This looks good.  Thanks for simplifying!

2018-11-13 06:25 UTC, donraab approved these changes
This looks good.  Thanks for adding the example with a for comprehension!

2018-11-13 06:25 UTC, donraab approved these changes
This looks good.  Thanks for simplifying!

2018-11-13 06:27 UTC, donraab commented on scala-module/src/main/scala/jvm/language/compare/scala/cards/ScalaDeckOfCards.scala
> +  val cards: List[Card] = Card.getCards.toList.sorted
We used toBuffer because we wanted to use mutable lists in each of the languages to be consistent.  I believe toList will return an immutable List correct?

2018-11-13 08:10 UTC, LogicalTime commented on scala-module/src/main/scala/jvm/language/compare/scala/cards/ScalaDeckOfCards.scala
> +  val cards: List[Card] = Card.getCards.toList.sorted
Yes, toList returns an immutable list. I'm fine with mutable list of you had a reason behind it. By default I generally make everything immutable. It makes reasoning about state easier and parallel/threadsafe programming as well. Anyways, if we can define a trait/interface to implement then I'd know the constraints I need to abide by for consistency. You might find that overkill though.

2018-11-13 15:52 UTC, LogicalTime commented
I switched back to the mutable collections and the shuffling three times. Using mutable collections like this will seem strange to many Scala developers. The principle is to use private mutable stuff when needed for performance and return a public result that is immutable. A common example would be a function using a string buffer internally and then returning the resulting string instead of the actual string buffer.

2018-11-14 00:31 UTC, donraab approved these changes
The changes looks good to me!  Thanks for taking the time to contribute @LogicalTime!

2018-11-17 20:57 UTC, LogicalTime commented
@donraab Hey Don, when will the changes be merged? Also, someone from the group had I question about a type inference issue in some other code. I would like to check that out. Could you find that and give me a link so I can play with it.

Note on code: Enumerations built into Scala are really light weight and useful for performance since they basically get type erased to integers at compile-time. Usually people use a sealed trait. with case objects that inherit the trait. Here for suit and rank, the Scala enumerations seem like a good choice. They aren't very likely to expand in complexity over time and performance might be a concern depending on what we do with the cards.

2018-11-18 01:56 UTC, merged

2018-11-18 01:57 UTC, nikhilnanivadekar commented
merged! Thanks for the code updates @LogicalTime